# Site settings
title: Shayna and Joseph Wedding
description: > # this means to ignore newlines until "baseurl:"
  Wedding Website for Shayna Kabiller and Joseph Booker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shaynaandjosephwedding.info" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
